version: '3.8'
services:
  database:
    # Official Postgres image from DockerHub (we use the last version)  docker-compose -f docker-compose.yaml up --build -d
    image: 'postgres:13.1-alpine'
    ports:
      - '5432:5432'

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: test # The PostgreSQL default database (automatically created at first launch)

volumes:
  cache:
    driver: local