spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: mypassword
  jpa:
    properties:
      hibernate:
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 100
        format_sql: true
        generate_statistics: false
        jdbc:
          time_zone: UTC
        default_schema: auth
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true
    open-in-view: false

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    enabled: true
  override-with-generic-response: false